# Generated by Django 3.0.5 on 2020-04-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpiece',
            name='description',
            field=models.CharField(default='hi', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterpiece',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
