# Generated by Django 3.0.5 on 2020-04-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynting', '0002_auto_20200427_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterpiece',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='masterpiece',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='masterpiece',
            name='image',
            field=models.ImageField(upload_to='static/media'),
        ),
    ]
