# Generated by Django 3.0.5 on 2020-04-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynting', '0003_auto_20200427_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpiece',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
