# Generated by Django 3.0.5 on 2020-04-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynting', '0004_auto_20200427_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpiece',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
