# Generated by Django 3.0.5 on 2020-04-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynting', '0006_masterpiece_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpiece',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
