# Generated by Django 3.0.5 on 2020-04-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paynting', '0007_auto_20200428_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='MadeWith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware', models.CharField(max_length=1000)),
                ('software', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Searches',
            },
        ),
        migrations.AddField(
            model_name='masterpiece',
            name='made_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paynting.MadeWith'),
        ),
    ]
