# Generated by Django 3.0.5 on 2020-04-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paynting', '0009_auto_20200429_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpiece',
            name='made_with',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paynting.MadeWith'),
        ),
    ]
