# Generated by Django 3.0.5 on 2020-04-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynting', '0010_auto_20200429_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpiece',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='masterpiece',
            name='masterpiece_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
