# Generated by Django 3.0.5 on 2020-04-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynting', '0013_auto_20200429_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_type', models.CharField(choices=[('az', 'A to Z'), ('za', 'Z to A')], max_length=2)),
            ],
        ),
    ]
