# Generated by Django 3.0.5 on 2020-04-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paynting', '0015_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
