# Generated by Django 3.0.5 on 2020-05-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynting', '0017_profile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='masterpiece',
            index=models.Index(fields=['masterpiece_name'], name='paynting_ma_masterp_0cbdc6_idx'),
        ),
    ]
